# Generated by Django 4.2.9 on 2024-03-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('platform', models.CharField(max_length=100)),
                ('link', models.URLField()),
            ],
        ),
    ]
